Document ModuleNotFoundError
tweag/jupyenv pull request #443
Opened 2023-02-27 05:09 UTC by erooke

Poetry does not lock down information about the build system used to build dependencies. As such poetry2nix cannot automatically figure out build inputs. https://github.com/nix-community/poetry2nix/issues/568

This documents how to help poetry2nix out with figuring out build inputs such as the issue in  #442

2023-03-02 13:53 UTC, erooke commented on docs/documentation/how-to.md
> +    kernel.python.python-with-numpy.overrides = overrides.nix;
Oops, yes I missed that. Fixed it in the most recent commit.

2023-03-03 19:47 UTC, djacu requested changes
Looks good. Just some minor feedback.

2023-03-03 19:47 UTC, djacu commented on docs/documentation/how-to.md
> +    ```
```suggestion
    ```nix title="kernels.nix"
    kernel.python.<yourKernelName>.overrides = ./overrides.nix;
    ```
```

2023-03-03 19:47 UTC, djacu commented on docs/documentation/how-to.md
> +    to your kernel.
```suggestion
    Note we used `"pathspec"` here as that was the package which generated the
    error and `final.flit-core` as that was the missing module. Add the override
    to your kernel.
```

2023-03-03 19:47 UTC, djacu commented on docs/documentation/how-to.md
> +    ```
Looks really good but let's use a generic placeholder for the kernel name so as not to confuse the user.

2023-03-04 19:42 UTC, djacu approved these changes

2023-03-04 19:53 UTC, merged